
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/credit-request-system
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true